In [2]:
import numpy as np

In [ ]:
# same data type
# multi-dimensional

# fast computation for arrays

In [3]:
# list -> ndarray 생성
# 데이터 타입을 float32로 설정
lst = [1,2,3]
a = np.array(lst)
a

array([1, 2, 3])

In [4]:
# 차원, 각 차원의 크기, 데이터 타입 출력
print(a.ndim)
print(a.shape)
print(a.dtype)

1
(3,)
int64


In [10]:
# 1로된 배열 생성 / 0으로된 배열 생성 / 0~2까지 0.2 간격의 배열 생성
a = np.ones((3,5))
b = np.zeros((2,3))
print(a)
print(b)

c = np.arange(0, 2, 0.2)
d = np.arange(1, 10.5, 0.5)
print(c)
print(d)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [18]:
# 0~1까지 100개의 요소를 갖는 배열 생성
a = np.linspace(0, 1, 101)
b = np.linspace(0, np.pi, 10)
print(a)
print(b)
c = np.exp([1,2,3])
print(c)

# [e^1, e^2, e^3]

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]
[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]
[ 2.71828183  7.3890561  20.08553692]


In [ ]:
# (2,2)의 배열 2개 생성 -> elementwise product / matrix product

In [27]:
# 0~12까지 (3,4) 배열 생성
# column 합 / row 최솟값 / 전체 최댓값
a = np.arange(0, 12, 1).reshape(3,4)
print(a)
print(a.ndim)
print(a.shape)

print(a.sum(axis=0))
print(a.sum(axis=1))

print(a.min(axis=0))
print(a.min(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
(3, 4)
[12 15 18 21]
[ 6 22 38]
[0 1 2 3]
[0 4 8]


In [ ]:
# 0~3까지 배열 생성
# e^ / root

In [49]:
# 0~12까지 (3,4) 배열 생성
# indexing / slicing
# iterating through rows
a = np.arange(0,12,1).reshape(3,4)
print(a)
print(a[0, 1])
print(a[1,2])
print(a[2,2])
print(a[0, :2])
print(a[0:2,2:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
1
6
10
[0 1]
[[2 3]
 [6 7]]


In [62]:
a = np.arange(10) **2
print(a)
# Slicing
print(a[2:5])
print(a[:5:2])  # equal to a[0:4:2]
print(a[4::2])  # equal to a[4:len(a):3]

print(a[:])
print(a[::-1])  # reversed array

[ 0  1  4  9 16 25 36 49 64 81]
[ 4  9 16]
[ 0  4 16]
[16 36 64]
[ 0  1  4  9 16 25 36 49 64 81]
[81 64 49 36 25 16  9  4  1  0]


In [78]:
a = np.floor(10 * np.random.random((3,4)))
print(a)
print(a.dtype)
print(a.T)
print(a.transpose())

[[0. 6. 0. 0.]
 [7. 3. 5. 3.]
 [2. 9. 8. 7.]]
float64
[[0. 7. 2.]
 [6. 3. 9.]
 [0. 5. 8.]
 [0. 3. 7.]]
[[0. 7. 2.]
 [6. 3. 9.]
 [0. 5. 8.]
 [0. 3. 7.]]


In [81]:
# 전치행렬
a = np.arange(10,).reshape(2,5).T
print(a)
print(a.shape)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
(5, 2)


In [83]:
a = np.floor(10*np.random.random((2, 2)))
b = np.floor(10*np.random.random((2, 2)))

print(a)
print(b)
print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[8. 8.]
 [0. 9.]]
[[8. 5.]
 [0. 4.]]
[[8. 8.]
 [0. 9.]
 [8. 5.]
 [0. 4.]]
[[8. 8. 8. 5.]
 [0. 9. 0. 4.]]


In [94]:
a = np.floor(10*np.random.random((2, 12)))

print(a)
c = np.hsplit(a, 4)
print(c[0])
print(c[1])
print(c[2])
print(c[3])
print(np.hstack((c[0], c[1], c[2], c[3])))

[[1. 5. 5. 9. 8. 6. 8. 5. 9. 3. 6. 9.]
 [5. 1. 7. 5. 3. 9. 7. 2. 4. 4. 5. 5.]]
[[1. 5. 5.]
 [5. 1. 7.]]
[[9. 8. 6.]
 [5. 3. 9.]]
[[8. 5. 9.]
 [7. 2. 4.]]
[[3. 6. 9.]
 [4. 5. 5.]]
[[1. 5. 5. 9. 8. 6. 8. 5. 9. 3. 6. 9.]
 [5. 1. 7. 5. 3. 9. 7. 2. 4. 4. 5. 5.]]


In [ ]:
# [0,1] 범위 내 난수의 (2,3) 배열 생성

# [1,5] 범위의 임의의 정수 (2,3) 배열 생성

# 표준정규분포를 따르는 난수의 (2,3) 배열 생성